#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin
export PATH

# Create a minimal subset of device and server nodes
/usr/lib/hurd/setup-translators -m -k -p

/hurd/mach-defpager

# Touch the first tty so that the Hurd console is certain to pick it
# and not some random other tty.
sleep 1
touch /dev/tty1

echo -n "Starting the Hurd console..."
console -d vga -g -d pc_kbd -c /dev/vcs &
sleep 1

# Switch over
exec < /dev/tty1 > /dev/tty1 2>&1
echo "Console started."

# Set the console device used by /sbin/reopen-console
echo /dev/tty1 >/var/run/console-device

export TERM=hurd

# Preset the terminal type for /lib/debian-installer/detect-console
export TERM_TYPE=virtual

# Export kernel parameters into environment, like Linux does.
for i in $*
do
  var=$(echo $i | sed "s/=.*$//")
  [ $var != $i ] || continue
  [ $var != root ] || continue
  val=$(echo $i | sed "s/^$var=//")
  echo $var is $val
  eval export $var=\$val
done

# Invoke init as linuxrc to work around pid != 1
exec /bin/busybox linuxrc

