#!/bin/sh

set -e

update-alternatives --quiet \
	--install /libexec/runsystem runsystem /libexec/runsystem.gnu 20

update-alternatives \
	--install /usr/bin/fakeroot fakeroot /bin/fakeroot-hurd 30

#DEBHELPER#

for i in vcs tty1 tty2 tty3 tty4 tty5 tty6; do
	if ! [ -e /dev/$i ]; then
		cd /dev
		/sbin/MAKEDEV $i || true
	fi
done

if [ ! -h /dev/mouse ]; then
  ln -s /dev/cons/mouse /dev/mouse
fi

if [ ! -h /dev/kbd ]; then
  ln -s /dev/cons/kbd /dev/kbd
fi
